### ISSUE TITLE
Problem with "no attribute findPosition"

### ISSUE THREAD

**Issue by LeXxyIT** [cvzone/cvzone#10]
All packages are installed.

pip list
```
Package               Version
--------------------- --------
absl-py               0.13.0
attrs                 21.2.0
cvzone                1.5.0
cycler                0.10.0
evdev                 1.4.0
kiwisolver            1.3.2
matplotlib            3.4.3
mediapipe             0.8.7.1
numpy                 1.21.2
opencv-contrib-python 4.5.3.56
opencv-python         4.5.3.56
Pillow                8.3.2
pip                   21.2.4
protobuf              3.17.3
pynput                1.7.3
pyparsing             2.4.7
python-dateutil       2.8.2
python-xlib           0.31
setuptools            57.4.0
six                   1.16.0
wheel                 0.36.2
```

I get code from your [example](https://github.com/cvzone/cvzone/blob/master/Examples/CornerRectangleExample.py).

Error:
```
Traceback (most recent call last):
  File "/var/www/examples/CornerRectangle.py", line 14, in <module>
    lmList, bbox = detector.findPosition(img, draw=False)
AttributeError: 'HandDetector' object has no attribute 'findPosition'
```

Then I try to install all this packages globally (without venv), and have the same error.

Where is an error?

**Comment by rafter-GMSVK** [comment]
findPositon was removed after cvzone 1.5

**Comment by LeXxyIT** [comment]
Which method I can use instead of findPositon?

**Comment by cvzone** [comment]
Solution 1: Use the same cvzone version used in the video. (After cvzone 1.5 the findPosition method is removed)
Solution 2: If you are using cvzone 1.5 or above use findHand method to get the landmarks. This video explains it in detail: https://youtu.be/3xfOa4yeOb0

**Comment by LeXxyIT** [comment]
Thank you!
