### ISSUE TITLE
cvzone facedetector error： AttributeError: module 'mediapipe.python.solutions.face_mesh' has no attribute 'FACE_CONNECTIONS' 

### ISSUE THREAD

**Issue by zealotCE** [cvzone/cvzone#11]
mediapipe renamed `FACE_CONNECTIONS`  to `FACEMESH_TESSELATION` .
please fixed it

links:
https://github.com/google/mediapipe/issues/2448
https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#python-solution-api

**Comment by erickthered** [comment]
I've created a pull request that addresses this issue.  Unfortunately the maintainer hasn't approved it yet.  You only need to change the name of a constant inside the face mesh detector: https://github.com/cvzone/cvzone/pull/15
