### ISSUE TITLE
in findDistance: x1, y1 = p1 ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Rishaw-Developer** [cvzone/cvzone#31]
### CODE
![dev1](https://user-images.githubusercontent.com/72737691/154239168-ca7ac714-fa6a-4dee-a6bb-4ae9db4b3356.PNG)
### Error
![dev2](https://user-images.githubusercontent.com/72737691/154239264-76d75f71-4cb4-4c69-b8ae-47bac4cbae06.PNG)
### My Solution
![dev3](https://user-images.githubusercontent.com/72737691/154239660-da2cbf36-bfe6-4b20-906e-dc28738448e8.PNG)

**Comment by leoluo1999** [comment]
I have the same problem, how to solve it？
