### ISSUE TITLE
Reverse order of RGB code in cvzone.cornerRect

### ISSUE THREAD

**Issue by sneetsher** [cvzone/cvzone#64]
Currently, the function `cvzone.cornerRect` take:

- `colorR` and `colorC` as BGR code, meaning as tuple: `(blue, green, red)`

Most user would expect the standard RGB:

- `(red, green, blue)`

**Comment by ayam04** [comment]
i can take up this issue if the author allows.

**Comment by murtazahassan** [comment]
This library is a wrapper of opencv which uses the BGR convention. 
Most of their flags contain BGR convention e.g. cv2.cvtColor(cv2.COLOR_BGR2GRAY)

Therefore we have kept the same convention.
