### ISSUE TITLE
Error In findFaceMesh

### ISSUE THREAD

**Issue by freeAhao** [cvzone/cvzone#9]
Version:

```
Package               Version
--------------------- --------
cvzone                1.4.1
mediapipe             0.8.7.1
```

Error message:

 ```
 File "./venv/lib/python3.9/site-packages/cvzone/FaceMeshModule.py", line 48, in findFaceMesh
    self.mpDraw.draw_landmarks(img, faceLms, self.mpFaceMesh.FACE_CONNECTIONS,
AttributeError: module 'mediapipe.python.solutions.face_mesh' has no attribute 'FACE_CONNECTIONS'
```

Change to None works

FaceMeshModule.py:

```
self.mpDraw.draw_landmarks(img, faceLms, None,
                                               self.drawSpec, self.drawSpec)
```

**Comment by erickthered** [comment]
I've created a pull request that addresses this issue. Unfortunately the maintainer hasn't approved it yet. You only need to change the name of a constant inside the face mesh detector: https://github.com/cvzone/cvzone/pull/15

**Comment by vwallajabad** [comment]
@Luca8991 u could also simply use ```pip install cvzone``` because sometimes the GitHub repo can be unstable. But the version in pypi.org will almost always be stable.
